eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: ORDER_DB_URL
      host: ORDER_DB_HOST
      port: ORDER_DB_PORT
      database: orderdb
      repositories:
        enabled: true